// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqSbP2sKVg9rbhuH6-YFYX2OQAtxVeDiY',
    appId: '1:990646993021:web:13d3cf75da344d7ec17114',
    messagingSenderId: '990646993021',
    projectId: 'match-food',
    authDomain: 'match-food.firebaseapp.com',
    storageBucket: 'match-food.appspot.com',
    measurementId: 'G-SFEKGBVZGE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1drp7CsjY8gt2sRKqL57RXDI1LMrjPQc',
    appId: '1:990646993021:android:d69ecd0f9f7e85d2c17114',
    messagingSenderId: '990646993021',
    projectId: 'match-food',
    storageBucket: 'match-food.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRFSmzYBrZ_O7ceDqjcWd2xw-BgjcycEw',
    appId: '1:990646993021:ios:2bc4f20325068310c17114',
    messagingSenderId: '990646993021',
    projectId: 'match-food',
    storageBucket: 'match-food.appspot.com',
    iosClientId: '990646993021-4t0p2jfhhsdoa7k5cnklg1qh4st7c54n.apps.googleusercontent.com',
    iosBundleId: 'com.example.matchFood',
  );
}
